
spring.application.name=videochat



spring.datasource.url=jdbc:mysql://localhost:3306/videochat
spring.datasource.username=root
spring.datasource.password=root



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=my-super-secret-key-for-video-chat-application-2026
jwt.expiration=3600000

server.port=${PORT:8080}
